import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {UserWrapper} from '@/app/context/userContext'
import { AppWrapper } from "./context/appContext";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}><AppWrapper><UserWrapper>{children}</UserWrapper></AppWrapper></body>
    </html>
  );
}
